apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cave-enki-backend
  name: cave-enki-backend
  namespace: cave-enki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cave-enki-backend
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cave-enki-backend
    spec:
      containers:
      - image: taghuofongue/cave-enki-backend
        name: cave-enki-backend
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
#        resources:
#          limits:
#            cpu: 0.2
#            memory: "200Mi"
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_DB_URL
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_USER

status: {}
