apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cave-enki-backend
  name: cave-enki-backend
  namespace: cave-enki
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app: cave-enki-backend
  type: LoadBalancer
status:
  loadBalancer: {}
